version: 2

updates:

- package-ecosystem: "github-actions"
  open-pull-requests-limit: 10
  directory: "/.github"
  schedule:
    interval: "monthly"
  target-branch: "update-lib"

- package-ecosystem: "npm"
  open-pull-requests-limit: 10
  directory: "/"
  schedule:
    interval: "monthly"
  target-branch: "update-lib"

- package-ecosystem: "cargo"
  open-pull-requests-limit: 10
  directory: "/src-tauri"
  schedule:
    interval: "monthly"
  target-branch: "update-lib"
